# --------------------------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
#     Template ID: 52
# </auto-generated>
# --------------------------------------------------------------------------------------------------

from typing import List, Union
from autoscript_sdb_microscope_client._sdb_microscope_client_extensions import SdbMicroscopeClientExtensions
from autoscript_core.common import CallRequest, DataType, DataTypeDefinition, UndefinedParameter


class SpecimenCurrent(object):    
    """
    The object provides control and status of the specimen current.
    """
    __slots__ = ["__id", "__application_client"]

    def __init__(self, application_client):
        self.__application_client = application_client
        self.__id = "SdbMicroscope.State.SpecimenCurrent"


    @property
    def value(self) -> 'float':        
        """
        The property retrieves current specimen current.
        """
        call_request = CallRequest(object_id=self.__id, method_name="Value_GET")
        call_response = self.__application_client._perform_call(call_request)
        if call_response.result.data_type != DataType.DOUBLE:
            raise TypeError("Incompatible type: specimen_current.value was expecting float, but server returned different object type: " + repr(call_response.result.data_type))

        return call_response.result.value

    @property
    def is_valid(self) -> 'bool':        
        """
        The property retrieves whether current specimen current is valid.
        """
        call_request = CallRequest(object_id=self.__id, method_name="IsValid_GET")
        call_response = self.__application_client._perform_call(call_request)
        if call_response.result.data_type != DataType.BOOL:
            raise TypeError("Incompatible type: specimen_current.is_valid was expecting bool, but server returned different object type: " + repr(call_response.result.data_type))

        return call_response.result.value
