# --------------------------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
#     Template ID: 52
# </auto-generated>
# --------------------------------------------------------------------------------------------------

from typing import List, Union
from autoscript_sdb_microscope_client._sdb_microscope_client_extensions import SdbMicroscopeClientExtensions
from autoscript_core.common import CallRequest, DataType, DataTypeDefinition
from .beams._electron_beam import ElectronBeam
from .beams._ion_beam import IonBeam


class Beams(object):
    """
    The object provides control and status of the microscope beams.
    """
    __slots__ = ["__id", "__application_client", "__electron_beam", "__ion_beam"]

    def __init__(self, application_client):
        self.__application_client = application_client
        self.__id = "SdbMicroscope.Beams"

        self.__electron_beam = ElectronBeam(self.__application_client)
        self.__ion_beam = IonBeam(self.__application_client)

    @property
    def electron_beam(self) -> 'ElectronBeam':
        """
        The object provides control and status of the electron beam.
        """
        return self.__electron_beam

    @property
    def ion_beam(self) -> 'IonBeam':
        """
        The object provides control and status of the ion beam.
        """
        return self.__ion_beam
