# --------------------------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
#     Template ID: 52
# </auto-generated>
# --------------------------------------------------------------------------------------------------

from typing import List, Union
from autoscript_sdb_microscope_client._sdb_microscope_client_extensions import SdbMicroscopeClientExtensions
from autoscript_core.common import CallRequest, DataType, DataTypeDefinition
from .autoscript._server import Server
from .autoscript._client import Client


class AutoScript(object):
    """
    The object provides service information regarding the AutoScript product.
    """
    __slots__ = ["__id", "__application_client", "__server", "__client"]

    def __init__(self, application_client):
        self.__application_client = application_client
        self.__id = "SdbMicroscope.Service.AutoScript"

        self.__server = Server(self.__application_client)
        self.__client = Client(self.__application_client)

    @property
    def server(self) -> 'Server':
        """
        The object provides service information regarding the AutoScript server.
        """
        return self.__server

    @property
    def client(self) -> 'Client':
        """
        The object provides service information regarding the AutoScript client.
        """
        return self.__client
