# --------------------------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
#     Template ID: 52
# </auto-generated>
# --------------------------------------------------------------------------------------------------

from typing import List, Union
from autoscript_sdb_microscope_client._sdb_microscope_client_extensions import SdbMicroscopeClientExtensions
from autoscript_core.common import CallRequest, DataType, DataTypeDefinition
from .beam_deceleration._stage_bias import StageBias


class BeamDeceleration(object):
    """
    The object provides control and status of the electron beam deceleration.
    """
    __slots__ = ["__id", "__application_client", "__stage_bias"]

    def __init__(self, application_client):
        self.__application_client = application_client
        self.__id = "SdbMicroscope.Beams.ElectronBeam.BeamDeceleration"

        self.__stage_bias = StageBias(self.__application_client)

    @property
    def stage_bias(self) -> 'StageBias':
        """
        The object provides control and status of the electron beam stage bias.
        """
        return self.__stage_bias

    def turn_on(self):
        """
        Turns the beam deceleration on.
        """
        call_request = CallRequest(object_id=self.__id, method_name="TurnOn", signature= [], parameters=[]) 
        call_response = self.__application_client._perform_call(call_request)

    def turn_off(self):
        """
        Turns the beam deceleration off.
        """
        call_request = CallRequest(object_id=self.__id, method_name="TurnOff", signature= [], parameters=[]) 
        call_response = self.__application_client._perform_call(call_request)

    @property
    def is_on(self) -> 'bool':
        """
        Returns True if the beam deceleration is turned on.
        """
        call_request = CallRequest(object_id=self.__id, method_name="IsOn_GET")
        call_response = self.__application_client._perform_call(call_request)
        if call_response.result.data_type != DataType.BOOL:
            raise TypeError("Incompatible type: beam_deceleration.is_on was expecting bool, but server returned different object type: " + repr(call_response.result.data_type))

        return call_response.result.value
