# --------------------------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
#     Template ID: 52
# </auto-generated>
# --------------------------------------------------------------------------------------------------

from typing import List, Union
from autoscript_sdb_microscope_client._sdb_microscope_client_extensions import SdbMicroscopeClientExtensions
from autoscript_core.common import CallRequest, DataType, DataTypeDefinition


class Source(object):
    """
    The object provides control and status of the electron beam source.
    """
    __slots__ = ["__id", "__application_client"]

    def __init__(self, application_client):
        self.__application_client = application_client
        self.__id = "SdbMicroscope.Beams.ElectronBeam.Source"


    @property
    def is_broken(self) -> 'bool':
        """
        The property returns true if the source needs to be replaced.
        """
        call_request = CallRequest(object_id=self.__id, method_name="IsBroken_GET")
        call_response = self.__application_client._perform_call(call_request)
        if call_response.result.data_type != DataType.BOOL:
            raise TypeError("Incompatible type: source.is_broken was expecting bool, but server returned different object type: " + repr(call_response.result.data_type))

        return call_response.result.value
