# --------------------------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
#     Template ID: 52
# </auto-generated>
# --------------------------------------------------------------------------------------------------

from typing import List, Union
from autoscript_sdb_microscope_client.structures import Point, Limits2d 
from autoscript_sdb_microscope_client._sdb_microscope_client_extensions import SdbMicroscopeClientExtensions
from autoscript_core.common import CallRequest, DataType, DataTypeDefinition, UndefinedParameter


class Stigmator(object):    
    """
    The object provides control and status of stigmator. It can be used to correct image astigmatism.
    """
    __slots__ = ["__id", "__application_client"]

    def __init__(self, application_client):
        self.__application_client = application_client
        self.__id = "SdbMicroscope.Beams.ElectronBeam.Stigmator"


    @property
    def limits(self) -> 'Limits2d':        
        """
        Retrieves the range of valid values.
        """
        call_request = CallRequest(object_id=self.__id, method_name="Limits_GET")
        call_response = self.__application_client._perform_call(call_request)
        if call_response.result.data_type != DataTypeDefinition(DataType.STRUCTURE_PRIMARY_ID, secondary_id="Limits2d"):
            raise TypeError("Incompatible type: stigmator.limits was expecting Limits2d, but server returned different object type: " + repr(call_response.result.data_type))

        return call_response.result.value

    @property
    def value(self) -> 'Point':        
        """
        Gets or sets the value.
        """
        call_request = CallRequest(object_id=self.__id, method_name="Value_GET")
        call_response = self.__application_client._perform_call(call_request)
        if call_response.result.data_type != DataTypeDefinition(DataType.STRUCTURE_PRIMARY_ID, secondary_id="Point"):
            raise TypeError("Incompatible type: stigmator.value was expecting Point, but server returned different object type: " + repr(call_response.result.data_type))

        return call_response.result.value

    @value.setter
    def value(self, value):        
        """
        Gets or sets the value.
        """
        call_request = CallRequest(object_id=self.__id, method_name="Value_SET", signature=[DataTypeDefinition(DataType.STRUCTURE_PRIMARY_ID, secondary_id="Point")], parameters=[value])
        if isinstance(value, Point):
            self.__application_client._perform_call(call_request)
        else:
            raise Exception("Cannot execute method with the given parameters combination. Read the documentation for details of how to call this method.")
