# --------------------------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
#     Template ID: 52
# </auto-generated>
# --------------------------------------------------------------------------------------------------

from typing import List, Union
from autoscript_sdb_microscope_client._sdb_microscope_client_extensions import SdbMicroscopeClientExtensions
from autoscript_core.common import CallRequest, DataType, DataTypeDefinition


class MdShutter(object):
    """
    The object representing Mirror Detector Shutter.
    """
    __slots__ = ["__id", "__application_client"]

    def __init__(self, application_client):
        self.__application_client = application_client
        self.__id = "SdbMicroscope.Detector.CustomSettings.MdShutter"


    def insert(self):
        """
        Inserts the Mirror Detector Shutter if possible.
        """
        call_request = CallRequest(object_id=self.__id, method_name="Insert", signature= [], parameters=[]) 
        call_response = self.__application_client._perform_call(call_request)

    def retract(self):
        """
        Retracts the Mirror Detector Shutter if possible.
        """
        call_request = CallRequest(object_id=self.__id, method_name="Retract", signature= [], parameters=[]) 
        call_response = self.__application_client._perform_call(call_request)

    @property
    def is_needed(self) -> 'bool':
        """
        Determines whether the Mirror Detector Shutter is needed.
        """
        call_request = CallRequest(object_id=self.__id, method_name="IsNeeded_GET")
        call_response = self.__application_client._perform_call(call_request)
        if call_response.result.data_type != DataType.BOOL:
            raise TypeError("Incompatible type: md_shutter.is_needed was expecting bool, but server returned different object type: " + repr(call_response.result.data_type))

        return call_response.result.value
