# --------------------------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
#     Template ID: 50
# </auto-generated>
# --------------------------------------------------------------------------------------------------

from autoscript_core.serialization import DynamicObjectHandle


class RectanglePatternHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(RectanglePatternHandle, self).__init__(id)


class LinePatternHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(LinePatternHandle, self).__init__(id)


class CirclePatternHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(CirclePatternHandle, self).__init__(id)


class CleaningCrossSectionPatternHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(CleaningCrossSectionPatternHandle, self).__init__(id)


class RegularCrossSectionPatternHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(RegularCrossSectionPatternHandle, self).__init__(id)


class StreamPatternHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(StreamPatternHandle, self).__init__(id)


class BitmapPatternHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(BitmapPatternHandle, self).__init__(id)


class GisPortHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(GisPortHandle, self).__init__(id)


class MultichemHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(MultichemHandle, self).__init__(id)


class ControlItemHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(ControlItemHandle, self).__init__(id)


class ControlItemPairHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(ControlItemPairHandle, self).__init__(id)


class ServerActionHandle(DynamicObjectHandle):
    __slots__ = []

    def __init__(self, id): 
        super(ServerActionHandle, self).__init__(id)
